### ISSUE TITLE
Error in building Project in Ubuntu 16.04

### ISSUE THREAD

**Issue by zzbazinga** [HospitalRun/hospitalrun-frontend#1154]
Encounter this error while building hospitalrun in Ubuntu 16.04:
I have node version 6 installed.

COMMAND: ember serve```

module.js:471
    throw err;
    ^

Error: Cannot find module 'jsonfile'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ammu/webapp/HR/hospitalrun-frontend/node_modules/fs-extra/lib/json/jsonfile.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by tangollama** [comment]
@zzbazinga can you offer steps to reproduce?

**Comment by zzbazinga** [comment]
I install with docket and it works fine.

**Comment by zzbazinga** [comment]
I don't remember steps so sorry.
