### ISSUE TITLE
Error during login

### ISSUE THREAD

**Issue by mrhmansour** [HospitalRun/hospitalrun-frontend#1292]
node_modules/hospitalrun-server-routes/routes/30-auth.js:165
                displayName: user.displayName,
                                 ^
TypeError: Cannot read property 'displayName' of undefined     at node_modules/hospitalrun-server-routes/routes/30-auth.js:165:34
    at node_modules/hospitalrun-server-routes/routes/30-auth.js:98:9
    at Request._callback (node_modules/nano/lib/nano.js:241:7)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**OS and Browser:** macOS, firefox

**Comment by jsl15c** [comment]
@mrhmansour I am unable to replicate this issue.

**Comment by p-mcgowan** [comment]
this may be because it expects "name" and not "username"

**Comment by DarkSoulCool** [comment]
If Demo I think Because the project owner changed ID or passwords .

**Comment by phurinaix** [comment]
It's expect name not username.

**Comment by stukalin** [comment]
@mrhmansour are you still able to repro this? Any other input would be appreciable. I'll put a label until we clarify that

**Comment by ashokaditya** [comment]
Hi @stukalin 

I see login name and password do not exist when trying to log in to the demo site at [login](https://beta.hospitalrun.io/#/login). using the credentials listed here [demo](http://hospitalrun.io/demo/)

Screenshots of login and server response:

<img width="539" alt="screen shot 2018-05-08 at 10 10 16" src="https://user-images.githubusercontent.com/1849116/39745620-0e1437da-52a8-11e8-97a7-31a34fb103c8.png">

<img width="1588" alt="screen shot 2018-05-08 at 10 12 39" src="https://user-images.githubusercontent.com/1849116/39745755-80ce01c0-52a8-11e8-98fb-13d040e0465f.png">

**Comment by jsl15c** [comment]
@ashokaditya  I think the request is taking too long or the client is cancelling the request before the server has time to respond.  So the credentials should work if this wasn't the case with the server.

Someone please correct me if this is an incorrect observation.

**Comment by ashokaditya** [comment]
@jsl15c I don't understand why would the client cancel the request? I see the response "says socket hang up" and another "config/" that doesn't load up on page load.

<img width="2560" alt="screen shot 2018-05-09 at 15 01 17" src="https://user-images.githubusercontent.com/1849116/39815990-22d5ae36-539a-11e8-92bc-2b2d7b5e2fa0.png">

<img width="1208" alt="screen shot 2018-05-09 at 15 00 28" src="https://user-images.githubusercontent.com/1849116/39815977-189720da-539a-11e8-8458-3cfe813b9439.png">
