### ISSUE TITLE
Bug: Undefined rule selector-no-id

### ISSUE THREAD

**Issue by DerekTBrown** [HospitalRun/hospitalrun-frontend#1302]
**Expected behavior:**
Stylelint executes without errors.

**Actual behavior:**
A bug occurs in executing stylelint:
```
web_1      | ======= Something went wrong running stylelint =======
web_1      | Undefined rule selector-no-id
web_1      | Error: Undefined rule selector-no-id
web_1      |     at module.exports (/usr/src/app/node_modules/broccoli-stylelint/node_modules/stylelint/lib/utils/configurationError.js:8:28)
web_1      |     at Object.keys.forEach.ruleName (/usr/src/app/node_modules/broccoli-stylelint/node_modules/stylelint/lib/augmentConfig.js:302:13)
web_1      |     at Array.forEach (native)
web_1      |     at normalizeAllRuleSettings (/usr/src/app/node_modules/broccoli-stylelint/node_modules/stylelint/lib/augmentConfig.js:297:29)
web_1      |     at augmentConfigBasic.then.then.then.augmentedConfig (/usr/src/app/node_modules/broccoli-stylelint/node_modules/stylelint/lib/augmentConfig.js:91:14)
```
**Steps to reproduce:**
Run using `ember-cli` or `docker-compose up`.

**OS and Browser:**
Docker Image

**Comment by DerekTBrown** [comment]
This appears to be because `selector-no-id` was deprecated:

https://github.com/stylelint/stylelint/issues/2528
