### ISSUE TITLE
Yarn Start - TypeError: Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by koshyviv** [HospitalRun/hospitalrun-frontend#1536]
**Expected behavior:**
The server to start and build. Expecting UI to be available.

**Actual behavior:**
It closes up with an error
```
Livereload server on http://localhost:7020
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: BrocText
_http_client.js:277
  req.emit('close');
     ^

TypeError: Cannot read property 'emit' of null
    at Socket.socketCloseListener (_http_client.js:277:6)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:509:12)
Done in 181.91s.

```

**Steps to reproduce:**
1. Clone Repo
2. `yarn install`
3. configure db
4. `yarn start`

**Screenshots (if applicable):**

**OS and Browser:**
OS - Win10
Browser - Chrome
Node - v6.14.4

**Comment by MatthewDorner** [comment]
I always get that error if I kill my CouchDB after I've already been up and running. I'm not sure why you're getting it on startup. If there's no CouchDB on starting the server, you usually get this:

```
Oops! Looks like CouchDB isn't running. CouchDB must be running before you can start HospitalRun.
For help or more info see https://github.com/HospitalRun/hospitalrun-frontend#install
```

So maybe your CouchDB is running but not configured correctly. Which version is CouchDB and what output did you get when you ran the initcouch.sh/initcouch2.sh script?

**Comment by koshyviv** [comment]
One deviation was that i directly updated the username pass in the couchdb `local.ini` file as `hradmin `and `test`. Then ran the script. Could that be an issue?

CouchDB - v1.7.1. On running the initcouch2.sh script. 
In the couch terminal
```
Eshell V6.4  (abort with ^G)
1> 
=INFO REPORT==== 21-Oct-2018::18:09:32 ===
    alarm_handler: {set,{{disk_almost_full,"D:\\"},[]}}
Apache CouchDB 1.7.1 (LogLevel=info) is starting.
Apache CouchDB has started. Time to relax.
[info] [<0.36.0>] Apache CouchDB has started on http://127.0.0.1:5984/
[info] [<0.110.0>] 127.0.0.1 - - PUT /_users/_security 200
[error] [<0.160.0>] Could not open file ../var/lib/couchdb/config.couch: file already exists
[info] [<0.111.0>] 127.0.0.1 - - PUT /config 412
[info] [<0.157.0>] 127.0.0.1 - - PUT /config/_security 200
[info] [<0.159.0>] 127.0.0.1 - - PUT /config/_design/auth 409
[error] [<0.176.0>] Could not open file ../var/lib/couchdb/main.couch: file already exists
[info] [<0.125.0>] 127.0.0.1 - - PUT /main 412
[info] [<0.124.0>] 127.0.0.1 - - PUT /main/_security 200
[info] [<0.163.0>] 127.0.0.1 - - PUT /main/_design/auth 409
[info] [<0.173.0>] 127.0.0.1 - - PUT /_node/couchdb@localhost/_config/http/authentication_handlers 400
[info] [<0.175.0>] 127.0.0.1 - - PUT /_node/couchdb@localhost/_config/couch_httpd_oauth/use_users_db 400
[info] [<0.178.0>] 127.0.0.1 - - PUT /_users/org.couchdb.user:hradmin 409

```

**Comment by koshyviv** [comment]
I think im doing something silly. It's working now, but there is some issue with the username and password.
```
Error creating push database! { Error: Name or password is incorrect.
    at Request._callback (F:\Misc\hospitalrun-frontend-master\hospitalrun-frontend-master\node_modules\nano\lib\nano.js:252:15)
    at Request.self.callback (F:\Misc\hospitalrun-frontend-master\hospitalrun-frontend-master\node_modules\request\request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (F:\Misc\hospitalrun-frontend-master\hospitalrun-frontend-master\node_modules\request\request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (F:\Misc\hospitalrun-frontend-master\hospitalrun-frontend-master\node_modules\request\request.js:1083:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'Error',
  error: 'unauthorized',
  reason: 'Name or password is incorrect.',
  scope: 'couch',
  statusCode: 401,
  request:
   { method: 'PUT',
     headers:
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/pushinfo' },
  headers:
   { date: 'Sun, 21 Oct 2018 12:50:36 GMT',
     'content-type': 'application/json',
     'cache-control': 'must-revalidate',
     statusCode: 401,
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/pushinfo' },
  errid: 'non_200',
  description: 'couch returned 401' }
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: BrocText
[API] Warning: Plugin uses .read/.rebuild API: ember-browserify
[API] Warning: Plugin uses .read/.rebuild API: ember-browserify
[API] Warning: Plugin uses .read/.rebuild API: BroccoliServiceWorker

Build successful (946286ms) – Serving on http://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel: hospitalrun (4)                        | 140347ms (35086 ms)
broccoli-persistent-filter:EslintValid... (2) | 98609ms (49304 ms)
Babel: ember-data (2)                         | 67951ms (33975 ms)
BroccoliMergeTrees (21)                       | 59206ms (2819 ms)
ember-browserify (2)                          | 54000ms (27000 ms)
TreeMerger (appAndDependencies) (2)           | 48068ms (24034 ms)
```

I suspect my DB conifg, Any idea on how i can approach to debug this?

**Comment by donaldwasserman** [comment]
I also haven’t seen that error. Although at the top it says disk almost full. Are you running couch locally or on a VM?

**Comment by donaldwasserman** [comment]
It looks like the disk is full. Are you running it on a VM?

**Comment by koshyviv** [comment]
My responses didn't come through I guess, I'm running couch on my local system

**Comment by koshyviv** [comment]
I'm running Couch locally.

**Comment by koshyviv** [comment]
I'm not sure if the comments are being populated, some issue with Github

I'm running on a local machine

**Comment by MatthewDorner** [comment]
maybe this, I think somebody else had it. https://github.com/apache/couchdb/issues/991

Try installing CouchDB to a file path with no spaces in it like C:\CouchDB

**Comment by tehKapa** [comment]
Hi @koshyviv! 
We're [now working on a new major version](https://github.com/HospitalRun/hospitalrun-frontend/issues/1605#issuecomment-518749445) (2.0) of HospitalRun. Sadly, your request can't be resolved, so we're forced to close this issue.
