### ISSUE TITLE
Node 5 support

### ISSUE THREAD

**Issue by richchurcher** [HospitalRun/hospitalrun-frontend#221]
Fresh installs with Node 4.x are spinning up nicely. Installs with 5.x succeed, but `ember serve` results in:

```
Build error

walkSync.entries is not a function
TypeError: walkSync.entries is not a function
    at Babel.Filter.build (/media/work/hospitalrun/hospitalrun-frontend/node_modules/broccoli-persistent-filter/index.js:65:26)
    at Babel.build (/media/work/hospitalrun/hospitalrun-frontend/node_modules/broccoli-babel-transpiler/index.js:72:33)
    at /media/work/hospitalrun/hospitalrun-frontend/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/media/work/hospitalrun/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/media/work/hospitalrun/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/media/work/hospitalrun/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/media/work/hospitalrun/hospitalrun-frontend/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```
It's not entirely clear, but this is likely to be an ember-cli issue as they're still recommending 4.0.

**Comment by stefanpenner** [comment]
> It's not entirely clear, but this is likely to be an ember-cli issue as they're still recommending 4.0.

No we support node 5, but many flavors of npm v3 are totally broken (they can't even install npm) I suspect this is what you may be hitting

**Comment by richchurcher** [comment]
That did the trick, thanks!

**Comment by stefanpenner** [comment]
@richchurcher ya, that release of npm has been giving us some grief. I hope node 5.x starts bundling one that works correctly asap.

**Comment by richchurcher** [comment]
It threw me because I mistakenly assumed that node 5.1.1 would've had an npm that was very recent! Apparently not recent enough. I might throw a note into the README to prevent people wasting time on it, as more upgrade from 4.x.
