### ISSUE TITLE
Fix warning during Incidents.test.tsx

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2453]
# 🐛 Bug Report
When running `Incidents.test.tsx`, there is a console error during the tests. 

```
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
          at module.exports (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at HTMLCanvasElementImpl.getContext (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
          at HTMLCanvasElement.getContext (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
          at Object.acquireContext (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/chart.js/dist/Chart.js:7769:49)
          at Chart.construct (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/chart.js/dist/Chart.js:9324:26)
          at new Chart (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/chart.js/dist/Chart.js:9311:7)
          at LineGraph.componentDidMount (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/@hospitalrun/components/src/components/Graph/LineGraph.tsx:89:18)
          at commitLifeCycles (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/react-dom/cjs/react-dom.development.js:19814:22)
          at commitLayoutEffects (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/react-dom/cjs/react-dom.development.js:22803:7)
          at HTMLUnknownElement.callCallback (/Users/jackcmeyer/git/hospitalrun/hospitalrun-frontend/node_modules/react-dom/cjs/react-dom.development.js:188:14) undefined
    console.error node_modules/chart.js/dist/Chart.js:9369
      Failed to create chart: can't acquire context from the given item

```

## To Reproduce
`npm test Incidents.test.tsx`

## Expected behavior
No warning should appear.

**Comment by blestab** [comment]
Thank you for the PR @ho1234c
