### ISSUE TITLE
Async error on Imaging list

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#365]
**Expected behavior:**
Imaging list renders.

**Actual behavior:**
Error: Assertion Failed: You looked up the 'patient' relationship on a 'imaging' with id 6C16C18A-1FCE-35A0-9777-47DD2F55C957 but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async (`DS.belongsTo({ async: true })`)
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26674:21)
    at assert (http://localhost:4200/assets/vendor.js:16436:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:26438:34)
    at assert (http://localhost:4200/assets/vendor.js:122930:37)
    at BelongsToRelationship.getRecord (http://localhost:4200/assets/vendor.js:129287:41)
    at get (http://localhost:4200/assets/vendor.js:128330:60)
    at Descriptor.ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:25256:28)
    at get (http://localhost:4200/assets/vendor.js:30915:19)
    at call (http://localhost:4200/assets/vendor.js:146276:37)

**Steps to reproduce:**
/imaging

**Screenshots (if applicable):**
<img width="1002" alt="screen shot 2016-03-16 at 9 05 19 am" src="https://cloud.githubusercontent.com/assets/929261/13819437/a371ff8a-eb56-11e5-9419-2b4c214f10bd.png">

**Comment by rohansp** [comment]
Does this occur on the demo link https://beta.hospitalrun.io/#/imaging ? Cause there it seems to be working fine.. Is this a local issue?

**Comment by tangollama** [comment]
@rohansp this appears to be an issues related to data deletion / migration. @jkleinsc is addressing from an architectural perspective. @jkleinsc do you think we should leave this open or assign to you?

**Comment by jkleinsc** [comment]
@tangollama I think we could close this in favor of #381, but we should change that issue to be more generic - i.e. Flag records as archived instead of deleted.

**Comment by jkleinsc** [comment]
Closing as this was resolved as part of #381
