### ISSUE TITLE
this._super.apply

### ISSUE THREAD

**Issue by gr2m** [HospitalRun/hospitalrun-frontend#473]
I followed the instructions but get this error. Any idea what it could be? 

```
$ npm start

> hospitalrun@0.9.11 start /Users/gregor/Projects/hospitalrun/frontend
> ./script/server

Checking CouchDB...Starting ember server
this._super.apply is not a function
TypeError: this._super.apply is not a function
    at Class.module.exports.init (/Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli-htmlbars/ember-addon-main.js:12:17)
    at new Class (/Users/gregor/Projects/hospitalrun/frontend/node_modules/core-object/core-object.js:18:12)
    at /Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli/lib/models/addons-factory.js:48:19
    at visit (/Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli/lib/models/addons-factory.js:44:9)
    at Class.Addon.initializeAddons (/Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli/lib/models/addon.js:222:36)
    at setupRegistryForEachAddon (/Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)
    at Class.Addon (/Users/gregor/Projects/hospitalrun/frontend/node_modules/ember-cli/lib/models/addon.js:109:5)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/gregor/.nvm/versions/node/v4.2.2/bin/node" "/Users/gregor/.nvm/versions/node/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! hospitalrun@0.9.11 start: `./script/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hospitalrun@0.9.11 start script './script/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hospitalrun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./script/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hospitalrun
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hospitalrun
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gregor/Projects/hospitalrun/frontend/npm-debug.log
```

**Versios**

MAC  10.11.4
node v4.2.2
npm 3.8.6

**Comment by jkleinsc** [comment]
@gr2m I think it is this:https://github.com/HospitalRun/hospitalrun-frontend/pull/472

**Comment by gr2m** [comment]
I tried it with `ember-cli-htmlbars@1.0.5` but got the same error. Must be something else

**Comment by jkleinsc** [comment]
I'm traveling right now, but

**Comment by jkleinsc** [comment]
I'll look into it when I get the chance

**Comment by jkleinsc** [comment]
@gr2m looks like #471 was the issue.  Pushing a fix soon.

**Comment by gr2m** [comment]
confirmed, thanks John!
